// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package browser

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockBrowser creates a new instance of MockBrowser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBrowser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBrowser {
	mock := &MockBrowser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBrowser is an autogenerated mock type for the Browser type
type MockBrowser struct {
	mock.Mock
}

type MockBrowser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBrowser) EXPECT() *MockBrowser_Expecter {
	return &MockBrowser_Expecter{mock: &_m.Mock}
}

// ActiveTabURL provides a mock function for the type MockBrowser
func (_mock *MockBrowser) ActiveTabURL() (string, bool, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ActiveTabURL")
	}

	var r0 string
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func() (string, bool, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() bool); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func() error); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockBrowser_ActiveTabURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ActiveTabURL'
type MockBrowser_ActiveTabURL_Call struct {
	*mock.Call
}

// ActiveTabURL is a helper method to define mock.On call
func (_e *MockBrowser_Expecter) ActiveTabURL() *MockBrowser_ActiveTabURL_Call {
	return &MockBrowser_ActiveTabURL_Call{Call: _e.mock.On("ActiveTabURL")}
}

func (_c *MockBrowser_ActiveTabURL_Call) Run(run func()) *MockBrowser_ActiveTabURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBrowser_ActiveTabURL_Call) Return(url string, ok bool, err error) *MockBrowser_ActiveTabURL_Call {
	_c.Call.Return(url, ok, err)
	return _c
}

func (_c *MockBrowser_ActiveTabURL_Call) RunAndReturn(run func() (string, bool, error)) *MockBrowser_ActiveTabURL_Call {
	_c.Call.Return(run)
	return _c
}
