version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
    groups:
      go-dependencies:
        patterns: ["*"]
        update-types: [minor, patch]
