all: true
dir: '{{.InterfaceDir}}'
structname: Mock{{.InterfaceName}}
pkgname: '{{.SrcPackageName}}'
filename: mock_{{.InterfaceName}}.go
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/joshmedeski/sesh:
    config:
      recursive: true
