# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sesh < Formula
  desc "Smart terminal session manager"
  homepage "https://github.com/joshmedeski/sesh"
  version "0.1.8"
  license "MIT"

  depends_on "tmux"
  depends_on "zoxide"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/joshmedeski/sesh/releases/download/v0.1.8/sesh_Darwin_arm64.tar.gz"
      sha256 "e0d56e0023239c6012338575c9688c7b3842ba3c338a24c3a37fa9e484108d62"

      def install
        bin.install "sesh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/joshmedeski/sesh/releases/download/v0.1.8/sesh_Darwin_x86_64.tar.gz"
      sha256 "3cdfc4aaee13085f17a1f11ea63fce663e35467f7ef144f01463af1bbeeafb8b"

      def install
        bin.install "sesh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joshmedeski/sesh/releases/download/v0.1.8/sesh_Linux_arm64.tar.gz"
      sha256 "b2d7ad4db29dc3687f9fe1f990ea609e375341a4192d8876f873b0b29b1c1ea0"

      def install
        bin.install "sesh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/joshmedeski/sesh/releases/download/v0.1.8/sesh_Linux_x86_64.tar.gz"
      sha256 "d0aeb8fbecc9b0f9f60646e9ded719d4f098d0e590cde3e5aa9fe2894edc9626"

      def install
        bin.install "sesh"
      end
    end
  end
end
