.TH SESH 1 "2024-01-31" MIT 

.SH NAME 
sesh

.SH DESfPIPTION
.B sesh \- Smart session manager for the terminal


.SH SYNOPSIS
sesh [global options] command [command options]

.SH GLOBAL OPTIONS
[\fB\-h\fP]
[\fB\-\-help\fP]
[\fB\-v\fP]
[\fB\-\-version\fP]

.SH COMMANDS 

.TP
\fBlist\fP, \fBl\fP 
List sessions

 
    \fB\-\-tmux\fP, \fB\-t\fP show tmux sessions  
    \fB\-\-zoxide\fP, \fB\-z\fP show zoxide results  
    \fB\-\-hide-attached\fP, \fB\-H\fP don't show currently attached sessions 

.TP
\fBchoose\fP, \fBch\fP 
Select session

 
    \fB\-\-tmux\fP, \fB\-t\fP show tmux sessions  
    \fB\-\-zoxide\fP, \fB\-z\fP show zoxide results  
    \fB\-\-hide-attached\fP, \fB\-H\fP don't show currently attached sessions 

.TP
\fBconnect\fP, \fBcn\fP 
Connect to the given session

 
    \fB\-\-switch\fP, \fB\-s\fP Always switch the session (and never attach). This is useful for third-party tools like Raycast.  
    \fB\-\-command\fP, \fB\-c\fP Execute a command when connecting to a new session. Will be ignored if the session exists. 

.TP
\fBclone\fP, \fBcl\fP 
Clone a git repo and connect to it as a session

 
    \fB\-\-cmdDir\fP, \fB\-d\fP The directory to run the git command in 



.SH EXAMPLES
sesh connect $(sesh list | fzf)

sesh connect --command nvim .

sesh list -tzH

sesh clone -d ~/sesh https://github.com/joshmedeski/sesh.git

.SH SEE ALSO
\fBhttps://github.com/joshmedeski/sesh\fP
