name: Test

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]
  workflow_call:

jobs:
  build:
    name: Build 🛠️
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v7
        with:
          go-version: "1.25"
      - name: Build all release targets
        uses: goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: "~> v2"
          args: build --snapshot --clean

  tests:
    name: Tests 🧪
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: "1.25"
      - name: Install junit report
        run: go install github.com/jstemmer/go-junit-report/v2@latest
      - name: Install mockery
        run: go install github.com/vektra/mockery/v3@latest
      - name: Create mocks
        run: mockery
      - name: Run tests
        run: go test -cover -bench=. -benchmem -race -v 2>&1 ./... | go-junit-report -set-exit-code > report.xml
      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: |
            report.xml
        if: always()
